debug yml script

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -17,30 +17,46 @@ jobs:
             HOSTNAME: ${{ secrets.SSH_HOST }}
             USER_NAME: ${{ secrets.SSH_USER }}
             GITHUB_TOKEN: ${{ secrets.GH_PAT }}
-
         run: |
-          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
-          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
+            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
+            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} << 'EOF'
+                echo "Signed in into ec2 via ssh!"
+                
+                echo "Stopping uvicorn and celery processes..."
+                
+                # Attempt to stop the uvicorn process
+                pgrep -f "uvicorn" || echo "uvicorn process not found"
+                pgrep -f "uvicorn" && pkill -f "uvicorn" || echo "No uvicorn process found"
+  
+                # Attempt to stop the celery process
+                pgrep -f "celery" || echo "celery process not found"
+                pgrep -f "celery" && pkill -f "celery" || echo "No celery process found"
+  
+                echo "uvicorn and celery stopped."
+            EOF
+        # run: |
+        #   echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
+        #   ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
 
-              # Now we have got the access of EC2 and we will start the deploy...
-              echo "Signed in into ec2 via ssh!"
-              echo "Stopping uvicorn and celery processes..."
-              pgrep -f "uvicorn" && pkill -f "uvicorn" || echo "No uvicorn process found"
-              pgrep -f "celery" && pkill -f "celery" || echo "No celery process found"
-              echo "uvicorn and celery stopped."
-              echo "Navigating into GMA directory..."
-              cd /home/ubuntu/${{ github.event.repository.name }} &&
-              pwd
-              echo "Pulling latest development build..."
-              git pull
-              echo "Latest development build pulled."
-              echo "Activating venv..."
-              source .venv/bin/activate
-              echo "venv activated."
-              echo "Starting uvicorn and celery..."
-              nohup python3 -m uvicorn main:app --host=0.0.0.0 &
-              nohup celery -A celery_config.celery_app worker --loglevel=info &
-              echo "uvicorn and celery started."
-              exit
-              echo "Signed out from ec2."
-              '
+        #       # Now we have got the access of EC2 and we will start the deploy...
+        #       echo "Signed in into ec2 via ssh!"
+        #       echo "Stopping uvicorn and celery processes..."
+        #       pgrep -f "uvicorn" && pkill -f "uvicorn" || echo "No uvicorn process found"
+        #       pgrep -f "celery" && pkill -f "celery" || echo "No celery process found"
+        #       echo "uvicorn and celery stopped."
+        #       echo "Navigating into GMA directory..."
+        #       cd /home/ubuntu/${{ github.event.repository.name }} &&
+        #       pwd
+        #       echo "Pulling latest development build..."
+        #       git pull
+        #       echo "Latest development build pulled."
+        #       echo "Activating venv..."
+        #       source .venv/bin/activate
+        #       echo "venv activated."
+        #       echo "Starting uvicorn and celery..."
+        #       nohup python3 -m uvicorn main:app --host=0.0.0.0 &
+        #       nohup celery -A celery_config.celery_app worker --loglevel=info &
+        #       echo "uvicorn and celery started."
+        #       exit
+        #       echo "Signed out from ec2."
+        #       '
